create-project:
	npm init

install-deps:
	npm i express mongodb mongoose bcryptjs validator jsonwebtoken node-cron

install-dev-deps:
	npm i env-cmd nodemon typescript ts-node-dev @types/express -D

generate-ts-config:
	npx tsc --init

start-project:
	npm run start
