AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "money-treck"

  # Create an IAM User
  S3AccessUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "money-treck-user"

  # Attach a policy to the IAM user for s3 access
  S3AccessPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "money-treck"
      Users:
        - Ref: "S3AccessUser"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}"
              - !Sub "arn:aws:s3:::${S3Bucket}/*"

  # Create an access key for the IAM user
  S3AccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref "S3AccessUser"

Outputs:
  # Output the S3 bucket name
  S3BucketName:
    Value: !Ref "S3Bucket"
    Description: "The name of the S3 bucket"

  # Output the access key ID
  AccessKeyId:
    Value: !Ref "S3AccessKey"
    Description: "The Access Key ID for the IAM user"

  # Output the secret access key
  SecretAccessKey:
    Value: !GetAtt "S3AccessKey.SecretAccessKey"
    Description: "The Secret Access Key for the IAM user"
